### PR TITLE
Fix compiler warning

### PR DESCRIPTION
**Pull request by dolfinus**
Hi.

During dependency compilation step I receive such a warning:
```
==> absinthe_error_payload
Compiling 6 files (.ex)
warning: redefining @doc attribute previously set at line 131.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head:

    @doc """
    new docs
    """
    def build_payload(...)

  lib/absinthe_error_payload/payload.ex:207: AbsintheErrorPayload.Payload.build_payload/2

Generated absinthe_error_payload app
```

Here I've fixed it and also added Elixir 1.11+OTP 23 checks into TravisCI matrix.

### CODE REVIEW

**Comment by dolfinus** [comment]
@simonprev @remi Could you please take a look at this?

**Comment by mrcasals** [comment]
Hi @simonprev @remi  could you check this PR, please? 😄

**Comment by remi** [comment]
Oh so sorry about that, I think it flew under my radar! Merging it now 😅

**Comment by remi** [comment]
Incoming v1.1.4 release! 🚀

**Comment by mrcasals** [comment]
Yay, thank you! 😄

**Pull request merged**
